name: Build and Deploy
on: 
  push:
  # 定时器
  schedule: 
    - cron: '0 9 * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Get Status
      run: npm install && npm run start

    - name: Send mail ✉️
      uses: dawidd6/action-send-mail@v3
      env:
          CPOLAR_EMAIL: ${{ secrets.CPOLAR_EMAIL }}
          CPOLAR_PASSWORD: ${{ secrets.CPOLAR_PASSWORD }}
      with:
        # smtp 服务器地址
        server_address: smtp.163.com
        # smtp 服务器端口
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: cpolar今日状态
        body: file://index.html
        to: 1772591173@qq.com
        from: GitHub Actions
        content_type: text/html
        convert_markdown: true
